name: mcr
channels:
  - https://software.repos.intel.com/python/conda
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy
  - pip
  - pip:
    - autograd
    - ezdxf
    - matplotlib
    - shapely
